---
title: "Dummy data overview"
output:
  html_document: default
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, eval=FALSE }
#library(LongitudinalDummyDataGenerator)
devtools::load_all(".")
```

```{r}
output_folder <- "../output_dummy_generator/"
```



# Generate service sector dummy data

```{r}
service_sector_data_version = "R12v1"
person_level_data_version="R12v1"
n_patients_minimum <- 5000
```


```{r, eval=FALSE}
tictoc::tic()
generate_all_dummy_data_to_files(
  output_folder = output_folder,
  service_sector_data_version = service_sector_data_version,
  person_level_data_version = person_level_data_version,
  n_patients_minimum = n_patients_minimum,
  seed = 13,
  nTreaths=(parallel::detectCores() -2)
)
tictoc::toc()

```

# Load data

```{r}

file_name <- stringr::str_c("dummy_service_sector_", service_sector_data_version, ".txt" )
service_sector_data <- readr::read_tsv(
  file.path(output_folder, file_name), 
  col_types = readr::cols(.default = readr::col_character()))

file_name <- stringr::str_c("dummy_minimum_extended_", person_level_data_version, ".txt" )
minimum_extended <- readr::read_tsv(file.path(output_folder, file_name))
```

# Assess data

## Patients overlap

```{r}
library(tidyverse)

bind_rows(
  service_sector_data |> distinct(FINNGENID) |> mutate(table="service_sector"),
  minimum_extended |> distinct(FINNGENID) |> mutate(table="minimum_extended")
) |> 
  group_by(FINNGENID) |> 
  summarise(Pathways = list(table)) |> 
  #
  ggplot(aes(x = Pathways)) +
  geom_bar() +
  ggupset::scale_x_upset()


```

## Vocabularies over time 

```{r}
service_sector_data_vocab <- service_sector_data |> 
  mutate(
    vocabulary = dplyr::case_when(
      SOURCE %in% c("INPAT", "OUTPAT") ~ ICDVER,
      SOURCE %in% c("PRIM_OUT", "OPER_IN", "OPER_OUT") ~ stringr::str_extract(CATEGORY, "^[:upper:]+"),
      SOURCE == "REIMB" ~ ICDVER,
      SOURCE == "PURCH" ~ "purch",
      SOURCE == "CANC" ~ "canc",
      SOURCE == "DEATH" ~ ICDVER
    ), 
    event_year = lubridate::year(APPROX_EVENT_DAY)
  ) 

```

```{r}
service_sector_data_vocab |> 
  count(SOURCE, vocabulary, event_year, name = "n_events") |> 
  #
  ggplot(aes(x=event_year, y=n_events, fill=vocabulary))+
  geom_bar(stat = "identity")+
  facet_grid(SOURCE~., scales = "free_y")+
    theme(legend.position="bottom")
```


## Visit type code calss over time 

```{r}
service_sector_visits <- service_sector_data |> distinct(SOURCE, INDEX, .keep_all = TRUE)
```


```{r}
service_sector_visits |> 
 mutate(
    VisitType_class = dplyr::case_when(
      SOURCE %in% c("INPAT", "OUTPAT", "OPER_IN", "OPER_OUT") & !is.na(CODE5) & is.na(CODE8) & is.na(CODE9) ~ "SOURCE | ServiceSector", 
      SOURCE %in% c("INPAT", "OUTPAT", "OPER_IN", "OPER_OUT") & !is.na(CODE5) & (!is.na(CODE8) | !is.na(CODE9)) ~ "SOURCE | ServiceSector AND SOURCE | Contact Type | Urgency", 
      SOURCE %in% c("INPAT", "OUTPAT", "OPER_IN", "OPER_OUT") & is.na(CODE5) & (!is.na(CODE8) | !is.na(CODE9)) ~ "SOURCE | Contact Type | Urgency", 
      SOURCE %in% c("PRIM_OUT") & (!is.na(CODE5) | !is.na(CODE6)) ~ "SOURCE | Contact Type | Service Type", 
      TRUE ~ "SOURCE"
    ), 
    event_year = lubridate::year(APPROX_EVENT_DAY)
  ) |> 
  count(SOURCE, VisitType_class, event_year, name = "n_visists") |> 
  #
  ggplot(aes(x=event_year, y=n_visists, fill=VisitType_class))+
  geom_bar(stat = "identity")+
  facet_grid(SOURCE~., scales = "free_y")+
    theme(legend.position="bottom", legend.direction="vertical")
```

## Provider code vocabulary over time 

```{r}

service_sector_visits |> 
 mutate(
    Provider_vocabulary = dplyr::case_when(
      SOURCE %in% c("INPAT", "OUTPAT", "OPER_IN", "OPER_OUT") & !is.na(CODE6) ~ "MEDSPECfi", 
      SOURCE %in% c("PRIM_OUT") & !is.na(CODE7) ~ "ProfessionalCode", 
      TRUE ~ "NA"
    ), 
    event_year = lubridate::year(APPROX_EVENT_DAY)
  ) |> 
  count(SOURCE, Provider_vocabulary, event_year, name = "n_visists") |> 
  #
  ggplot(aes(x=event_year, y=n_visists, fill=Provider_vocabulary))+
  geom_bar(stat = "identity")+
  facet_grid(SOURCE~., scales = "free_y")+
    theme(legend.position="bottom")
```
